[package]
name = "cjtoolkit-structured-validator"
version = "0.1.0"
edition = "2024"

[features]
url = ["dep:url"]

[dependencies]
unicode-segmentation = "1.12.0"
thiserror = "2.0.16"
blake3 = "1.8.2"
url = { version = "2.5.7", optional = true }